ALTER TABLE hosts ADD COLUMN host_info_xml TEXT NOT NULL DEFAULT '';
ALTER TABLE hosts ADD COLUMN run_mode TEXT NOT NULL DEFAULT '';
ALTER TABLE hosts ADD COLUMN opaque_data TEXT NOT NULL DEFAULT '';
