ALTER TABLE user_projects ADD COLUMN pending_detach BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE user_projects ADD COLUMN detach_when_done BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE user_projects ADD COLUMN is_weak_auth BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE user_projects ADD COLUMN last_error TEXT;
ALTER TABLE user_projects ADD COLUMN consecutive_failures INT NOT NULL DEFAULT 0;
