ALTER TABLE user_projects ADD COLUMN total_credit REAL NOT NULL DEFAULT 0;
ALTER TABLE user_projects ADD COLUMN recent_credit REAL NOT NULL DEFAULT 0;
ALTER TABLE user_projects ADD COLUMN last_info_sync TIMESTAMPTZ;

ALTER TABLE users ADD COLUMN is_admin BOOLEAN NOT NULL DEFAULT FALSE;
